
export default {
	FEEDS_RECEIVED: 'FEEDS_RECEIVED',

	USERS_RECEIVED: 		'USERS_RECEIVED',
	USER_CREATED: 			'USER_CREATED',
	USER_LOGGED_IN: 		'USER_LOGGED_IN',
	CURRENT_USER_RECEIVED: 	'CURRENT_USER_RECEIVED'

}